/* Generated by Yosys 0.44+9 (git sha1 4b9f45273, g++ 11.4.0-1ubuntu1~22.04 -fPIC -fPIC -O3) */

module top(clk, rst, x, enable, din, spike);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire \blocco3.fsm.q[0] ;
  wire \blocco3.fsm.q[10] ;
  wire \blocco3.fsm.q[11] ;
  wire \blocco3.fsm.q[1] ;
  wire \blocco3.fsm.q[2] ;
  wire \blocco3.fsm.q[3] ;
  wire \blocco3.fsm.q[4] ;
  wire \blocco3.fsm.q[5] ;
  wire \blocco3.fsm.q[6] ;
  wire \blocco3.fsm.q[7] ;
  wire \blocco3.fsm.q[8] ;
  wire \blocco3.fsm.q[9] ;
  wire \blocco3.fsm.soglia[0] ;
  wire \blocco3.fsm.soglia[10] ;
  wire \blocco3.fsm.soglia[11] ;
  wire \blocco3.fsm.soglia[1] ;
  wire \blocco3.fsm.soglia[2] ;
  wire \blocco3.fsm.soglia[3] ;
  wire \blocco3.fsm.soglia[4] ;
  wire \blocco3.fsm.soglia[5] ;
  wire \blocco3.fsm.soglia[6] ;
  wire \blocco3.fsm.soglia[7] ;
  wire \blocco3.fsm.soglia[8] ;
  wire \blocco3.fsm.soglia[9] ;
  wire \blocco3.fsm.stato_corrente[0] ;
  wire \blocco3.fsm.stato_corrente[1] ;
  wire \blocco3.fsm.stato_corrente[2] ;
  input clk;
  wire clk;
  input din;
  wire din;
  input enable;
  wire enable;
  input rst;
  wire rst;
  output spike;
  wire spike;
  input [10:0] x;
  wire [10:0] x;
  wire \z[0] ;
  wire \z[10] ;
  wire \z[1] ;
  wire \z[2] ;
  wire \z[3] ;
  wire \z[4] ;
  wire \z[5] ;
  wire \z[6] ;
  wire \z[7] ;
  wire \z[8] ;
  wire \z[9] ;
  NOR2_X1 _113_ (
    .A1(\blocco3.fsm.stato_corrente[0] ),
    .A2(\blocco3.fsm.stato_corrente[1] ),
    .ZN(_047_)
  );
  AND2_X1 _114_ (
    .A1(\blocco3.fsm.stato_corrente[2] ),
    .A2(_047_),
    .ZN(spike)
  );
  INV_X1 _115_ (
    .A(\blocco3.fsm.soglia[11] ),
    .ZN(_048_)
  );
  NAND2_X1 _116_ (
    .A1(_048_),
    .A2(\blocco3.fsm.q[11] ),
    .ZN(_049_)
  );
  XOR2_X1 _117_ (
    .A(\blocco3.fsm.soglia[1] ),
    .B(\blocco3.fsm.q[1] ),
    .Z(_050_)
  );
  INV_X1 _118_ (
    .A(\blocco3.fsm.q[0] ),
    .ZN(_051_)
  );
  AOI21_X1 _119_ (
    .A(_050_),
    .B1(_051_),
    .B2(\blocco3.fsm.soglia[0] ),
    .ZN(_052_)
  );
  XOR2_X1 _120_ (
    .A(\blocco3.fsm.soglia[3] ),
    .B(\blocco3.fsm.q[3] ),
    .Z(_053_)
  );
  XOR2_X1 _121_ (
    .A(\blocco3.fsm.soglia[2] ),
    .B(\blocco3.fsm.q[2] ),
    .Z(_054_)
  );
  NOR2_X1 _122_ (
    .A1(_053_),
    .A2(_054_),
    .ZN(_055_)
  );
  OAI211_X1 _123_ (
    .A(_052_),
    .B(_055_),
    .C1(\blocco3.fsm.soglia[0] ),
    .C2(_051_),
    .ZN(_056_)
  );
  XOR2_X1 _124_ (
    .A(\blocco3.fsm.soglia[11] ),
    .B(\blocco3.fsm.q[11] ),
    .Z(_057_)
  );
  XOR2_X1 _125_ (
    .A(\blocco3.fsm.soglia[10] ),
    .B(\blocco3.fsm.q[10] ),
    .Z(_058_)
  );
  NOR2_X1 _126_ (
    .A1(_057_),
    .A2(_058_),
    .ZN(_059_)
  );
  XNOR2_X1 _127_ (
    .A(\blocco3.fsm.soglia[9] ),
    .B(\blocco3.fsm.q[9] ),
    .ZN(_060_)
  );
  XNOR2_X1 _128_ (
    .A(\blocco3.fsm.soglia[8] ),
    .B(\blocco3.fsm.q[8] ),
    .ZN(_061_)
  );
  NAND3_X1 _129_ (
    .A1(_059_),
    .A2(_060_),
    .A3(_061_),
    .ZN(_062_)
  );
  XNOR2_X1 _130_ (
    .A(\blocco3.fsm.soglia[7] ),
    .B(\blocco3.fsm.q[7] ),
    .ZN(_063_)
  );
  XNOR2_X1 _131_ (
    .A(\blocco3.fsm.soglia[6] ),
    .B(\blocco3.fsm.q[6] ),
    .ZN(_064_)
  );
  INV_X1 _132_ (
    .A(\blocco3.fsm.soglia[4] ),
    .ZN(_065_)
  );
  INV_X1 _133_ (
    .A(\blocco3.fsm.soglia[5] ),
    .ZN(_066_)
  );
  AOI22_X1 _134_ (
    .A1(_065_),
    .A2(\blocco3.fsm.q[4] ),
    .B1(\blocco3.fsm.q[5] ),
    .B2(_066_),
    .ZN(_067_)
  );
  INV_X1 _135_ (
    .A(\blocco3.fsm.q[4] ),
    .ZN(_068_)
  );
  INV_X1 _136_ (
    .A(\blocco3.fsm.q[5] ),
    .ZN(_069_)
  );
  AOI22_X1 _137_ (
    .A1(\blocco3.fsm.soglia[4] ),
    .A2(_068_),
    .B1(_069_),
    .B2(\blocco3.fsm.soglia[5] ),
    .ZN(_070_)
  );
  NAND4_X1 _138_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_067_),
    .A4(_070_),
    .ZN(_071_)
  );
  OR2_X1 _139_ (
    .A1(_062_),
    .A2(_071_),
    .ZN(_072_)
  );
  INV_X1 _140_ (
    .A(\blocco3.fsm.soglia[1] ),
    .ZN(_073_)
  );
  AND2_X1 _141_ (
    .A1(_073_),
    .A2(\blocco3.fsm.q[1] ),
    .ZN(_074_)
  );
  OAI21_X1 _142_ (
    .A(_055_),
    .B1(_052_),
    .B2(_074_),
    .ZN(_075_)
  );
  INV_X1 _143_ (
    .A(\blocco3.fsm.q[2] ),
    .ZN(_076_)
  );
  NOR3_X1 _144_ (
    .A1(\blocco3.fsm.soglia[2] ),
    .A2(_076_),
    .A3(_053_),
    .ZN(_077_)
  );
  INV_X1 _145_ (
    .A(\blocco3.fsm.soglia[3] ),
    .ZN(_078_)
  );
  AOI21_X1 _146_ (
    .A(_077_),
    .B1(\blocco3.fsm.q[3] ),
    .B2(_078_),
    .ZN(_079_)
  );
  AOI211_X1 _147_ (
    .A(_062_),
    .B(_071_),
    .C1(_075_),
    .C2(_079_),
    .ZN(_080_)
  );
  INV_X1 _148_ (
    .A(\blocco3.fsm.soglia[8] ),
    .ZN(_081_)
  );
  INV_X1 _149_ (
    .A(\blocco3.fsm.soglia[9] ),
    .ZN(_082_)
  );
  AOI22_X1 _150_ (
    .A1(_081_),
    .A2(\blocco3.fsm.q[8] ),
    .B1(\blocco3.fsm.q[9] ),
    .B2(_082_),
    .ZN(_083_)
  );
  OAI21_X1 _151_ (
    .A(_059_),
    .B1(\blocco3.fsm.q[9] ),
    .B2(_082_),
    .ZN(_084_)
  );
  NOR2_X1 _152_ (
    .A1(_083_),
    .A2(_084_),
    .ZN(_085_)
  );
  INV_X1 _153_ (
    .A(\blocco3.fsm.soglia[10] ),
    .ZN(_086_)
  );
  NAND2_X1 _154_ (
    .A1(_086_),
    .A2(\blocco3.fsm.q[10] ),
    .ZN(_087_)
  );
  OAI21_X1 _155_ (
    .A(_049_),
    .B1(_057_),
    .B2(_087_),
    .ZN(_088_)
  );
  INV_X1 _156_ (
    .A(\blocco3.fsm.soglia[6] ),
    .ZN(_089_)
  );
  INV_X1 _157_ (
    .A(\blocco3.fsm.soglia[7] ),
    .ZN(_090_)
  );
  AOI22_X1 _158_ (
    .A1(_089_),
    .A2(\blocco3.fsm.q[6] ),
    .B1(\blocco3.fsm.q[7] ),
    .B2(_090_),
    .ZN(_091_)
  );
  NOR2_X1 _159_ (
    .A1(_090_),
    .A2(\blocco3.fsm.q[7] ),
    .ZN(_092_)
  );
  OAI211_X1 _160_ (
    .A(_063_),
    .B(_064_),
    .C1(_066_),
    .C2(\blocco3.fsm.q[5] ),
    .ZN(_093_)
  );
  OAI22_X1 _161_ (
    .A1(_091_),
    .A2(_092_),
    .B1(_067_),
    .B2(_093_),
    .ZN(_094_)
  );
  AND4_X1 _162_ (
    .A1(_059_),
    .A2(_060_),
    .A3(_061_),
    .A4(_094_),
    .ZN(_095_)
  );
  OR4_X1 _163_ (
    .A1(_080_),
    .A2(_085_),
    .A3(_088_),
    .A4(_095_),
    .ZN(_096_)
  );
  OAI221_X1 _164_ (
    .A(_049_),
    .B1(_056_),
    .B2(_072_),
    .C1(_096_),
    .C2(_057_),
    .ZN(_097_)
  );
  OAI211_X1 _165_ (
    .A(_000_),
    .B(\blocco3.fsm.stato_corrente[0] ),
    .C1(\blocco3.fsm.stato_corrente[1] ),
    .C2(_097_),
    .ZN(_098_)
  );
  INV_X1 _166_ (
    .A(clk),
    .ZN(_015_)
  );
  NAND3_X1 _167_ (
    .A1(\blocco3.fsm.stato_corrente[2] ),
    .A2(\blocco3.fsm.stato_corrente[0] ),
    .A3(\blocco3.fsm.stato_corrente[1] ),
    .ZN(_016_)
  );
  NAND2_X1 _168_ (
    .A1(_015_),
    .A2(_016_),
    .ZN(_017_)
  );
  NAND2_X1 _169_ (
    .A1(\blocco3.fsm.stato_corrente[0] ),
    .A2(\blocco3.fsm.stato_corrente[1] ),
    .ZN(_018_)
  );
  AOI21_X1 _170_ (
    .A(_097_),
    .B1(_018_),
    .B2(\blocco3.fsm.stato_corrente[2] ),
    .ZN(_019_)
  );
  INV_X1 _171_ (
    .A(\blocco3.fsm.stato_corrente[1] ),
    .ZN(_020_)
  );
  NOR3_X1 _172_ (
    .A1(\blocco3.fsm.stato_corrente[2] ),
    .A2(\blocco3.fsm.stato_corrente[0] ),
    .A3(_020_),
    .ZN(_021_)
  );
  AND2_X1 _173_ (
    .A1(_048_),
    .A2(\blocco3.fsm.q[11] ),
    .ZN(_022_)
  );
  NOR2_X1 _174_ (
    .A1(_056_),
    .A2(_072_),
    .ZN(_023_)
  );
  NOR4_X1 _175_ (
    .A1(_080_),
    .A2(_085_),
    .A3(_088_),
    .A4(_095_),
    .ZN(_024_)
  );
  XNOR2_X1 _176_ (
    .A(\blocco3.fsm.soglia[11] ),
    .B(\blocco3.fsm.q[11] ),
    .ZN(_025_)
  );
  AOI211_X1 _177_ (
    .A(_022_),
    .B(_023_),
    .C1(_024_),
    .C2(_025_),
    .ZN(_026_)
  );
  OAI211_X1 _178_ (
    .A(_015_),
    .B(_016_),
    .C1(_021_),
    .C2(_026_),
    .ZN(_027_)
  );
  OAI22_X1 _179_ (
    .A1(_098_),
    .A2(_017_),
    .B1(_019_),
    .B2(_027_),
    .ZN(_014_)
  );
  AND2_X1 _180_ (
    .A1(\blocco3.fsm.stato_corrente[0] ),
    .A2(_020_),
    .ZN(_028_)
  );
  OAI21_X1 _181_ (
    .A(_028_),
    .B1(_000_),
    .B2(\blocco3.fsm.stato_corrente[2] ),
    .ZN(_029_)
  );
  INV_X1 _182_ (
    .A(_021_),
    .ZN(_030_)
  );
  AOI21_X1 _183_ (
    .A(_027_),
    .B1(_029_),
    .B2(_030_),
    .ZN(_013_)
  );
  NAND2_X1 _184_ (
    .A1(_000_),
    .A2(_028_),
    .ZN(_031_)
  );
  AOI21_X1 _185_ (
    .A(_021_),
    .B1(_047_),
    .B2(_000_),
    .ZN(_032_)
  );
  MUX2_X1 _186_ (
    .A(_031_),
    .B(_032_),
    .S(_026_),
    .Z(_033_)
  );
  NOR2_X1 _187_ (
    .A1(clk),
    .A2(_033_),
    .ZN(_012_)
  );
  NOR2_X1 _188_ (
    .A1(\blocco3.fsm.soglia[9] ),
    .A2(enable),
    .ZN(_034_)
  );
  AOI211_X1 _189_ (
    .A(rst),
    .B(_034_),
    .C1(enable),
    .C2(_081_),
    .ZN(_011_)
  );
  NOR2_X1 _190_ (
    .A1(\blocco3.fsm.soglia[8] ),
    .A2(enable),
    .ZN(_035_)
  );
  AOI211_X1 _191_ (
    .A(rst),
    .B(_035_),
    .C1(_090_),
    .C2(enable),
    .ZN(_010_)
  );
  NOR2_X1 _192_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[7] ),
    .ZN(_036_)
  );
  AOI211_X1 _193_ (
    .A(rst),
    .B(_036_),
    .C1(_089_),
    .C2(enable),
    .ZN(_009_)
  );
  NOR2_X1 _194_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[6] ),
    .ZN(_037_)
  );
  AOI211_X1 _195_ (
    .A(rst),
    .B(_037_),
    .C1(_066_),
    .C2(enable),
    .ZN(_008_)
  );
  NOR2_X1 _196_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[5] ),
    .ZN(_038_)
  );
  AOI211_X1 _197_ (
    .A(rst),
    .B(_038_),
    .C1(_065_),
    .C2(enable),
    .ZN(_007_)
  );
  NOR2_X1 _198_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[4] ),
    .ZN(_039_)
  );
  AOI211_X1 _199_ (
    .A(rst),
    .B(_039_),
    .C1(_078_),
    .C2(enable),
    .ZN(_006_)
  );
  NOR2_X1 _200_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[3] ),
    .ZN(_040_)
  );
  INV_X1 _201_ (
    .A(\blocco3.fsm.soglia[2] ),
    .ZN(_041_)
  );
  AOI211_X1 _202_ (
    .A(rst),
    .B(_040_),
    .C1(_041_),
    .C2(enable),
    .ZN(_005_)
  );
  NOR2_X1 _203_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[2] ),
    .ZN(_042_)
  );
  AOI211_X1 _204_ (
    .A(rst),
    .B(_042_),
    .C1(_073_),
    .C2(enable),
    .ZN(_004_)
  );
  NOR2_X1 _205_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[1] ),
    .ZN(_043_)
  );
  INV_X1 _206_ (
    .A(\blocco3.fsm.soglia[0] ),
    .ZN(_044_)
  );
  AOI211_X1 _207_ (
    .A(rst),
    .B(_043_),
    .C1(_044_),
    .C2(enable),
    .ZN(_003_)
  );
  NOR2_X1 _208_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[11] ),
    .ZN(_045_)
  );
  AOI211_X1 _209_ (
    .A(rst),
    .B(_045_),
    .C1(_086_),
    .C2(enable),
    .ZN(_002_)
  );
  NOR2_X1 _210_ (
    .A1(enable),
    .A2(\blocco3.fsm.soglia[10] ),
    .ZN(_046_)
  );
  AOI211_X1 _211_ (
    .A(rst),
    .B(_046_),
    .C1(enable),
    .C2(_082_),
    .ZN(_001_)
  );
  iir blocco1 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .z({ \z[10] , \z[9] , \z[8] , \z[7] , \z[6] , \z[5] , \z[4] , \z[3] , \z[2] , \z[1] , \z[0]  })
  );
  enfasi blocco2 (
    .clk(clk),
    .q({ \blocco3.fsm.q[11] , \blocco3.fsm.q[10] , \blocco3.fsm.q[9] , \blocco3.fsm.q[8] , \blocco3.fsm.q[7] , \blocco3.fsm.q[6] , \blocco3.fsm.q[5] , \blocco3.fsm.q[4] , \blocco3.fsm.q[3] , \blocco3.fsm.q[2] , \blocco3.fsm.q[1] , \blocco3.fsm.q[0]  }),
    .rst(rst),
    .z({ \z[10] , \z[9] , \z[8] , \z[7] , \z[6] , \z[5] , \z[4] , \z[3] , \z[2] , \z[1] , \z[0]  })
  );
  DFF_X1 \blocco3.fsm.soglia[0]$_DFF_P_  (
    .CK(clk),
    .D(din),
    .Q(\blocco3.fsm.soglia[0] ),
    .QN(_112_)
  );
  DFF_X1 \blocco3.fsm.soglia[10]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_001_),
    .Q(\blocco3.fsm.soglia[10] ),
    .QN(_111_)
  );
  DFF_X1 \blocco3.fsm.soglia[11]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_002_),
    .Q(\blocco3.fsm.soglia[11] ),
    .QN(_110_)
  );
  DFF_X1 \blocco3.fsm.soglia[1]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_003_),
    .Q(\blocco3.fsm.soglia[1] ),
    .QN(_109_)
  );
  DFF_X1 \blocco3.fsm.soglia[2]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_004_),
    .Q(\blocco3.fsm.soglia[2] ),
    .QN(_108_)
  );
  DFF_X1 \blocco3.fsm.soglia[3]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_005_),
    .Q(\blocco3.fsm.soglia[3] ),
    .QN(_107_)
  );
  DFF_X1 \blocco3.fsm.soglia[4]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_006_),
    .Q(\blocco3.fsm.soglia[4] ),
    .QN(_106_)
  );
  DFF_X1 \blocco3.fsm.soglia[5]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_007_),
    .Q(\blocco3.fsm.soglia[5] ),
    .QN(_105_)
  );
  DFF_X1 \blocco3.fsm.soglia[6]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_008_),
    .Q(\blocco3.fsm.soglia[6] ),
    .QN(_104_)
  );
  DFF_X1 \blocco3.fsm.soglia[7]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_009_),
    .Q(\blocco3.fsm.soglia[7] ),
    .QN(_103_)
  );
  DFF_X1 \blocco3.fsm.soglia[8]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_010_),
    .Q(\blocco3.fsm.soglia[8] ),
    .QN(_102_)
  );
  DFF_X1 \blocco3.fsm.soglia[9]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_011_),
    .Q(\blocco3.fsm.soglia[9] ),
    .QN(_101_)
  );
  DFF_X1 \blocco3.fsm.stato_corrente[0]$_SDFF_PP0_  (
    .CK(clk),
    .D(_012_),
    .Q(\blocco3.fsm.stato_corrente[0] ),
    .QN(_100_)
  );
  DFF_X1 \blocco3.fsm.stato_corrente[1]$_SDFF_PP0_  (
    .CK(clk),
    .D(_013_),
    .Q(\blocco3.fsm.stato_corrente[1] ),
    .QN(_099_)
  );
  DFF_X1 \blocco3.fsm.stato_corrente[2]$_SDFF_PP0_  (
    .CK(clk),
    .D(_014_),
    .Q(\blocco3.fsm.stato_corrente[2] ),
    .QN(_000_)
  );
endmodule
